const ADMIN_ID = 'nyj5004';
const BETA_MANAGER_ID = 'manager247';
const INVITE_CODE = 'sfbt2630';
const INVITE_LIMIT = 30;
const DEFAULT_STUDENTS = ['hy', 'yjw', 'nyj'];
const DEFAULT_DISPLAY_NAMES = {hy:'하윤', yjw:'윤재욱'};
const RESERVED_IDS = new Set([ADMIN_ID, BETA_MANAGER_ID]);
let schemaReady = false;

function nowIso(){ return new Date().toISOString(); }
function uid(prefix='id'){ return `${prefix}_${Date.now().toString(36)}_${crypto.randomUUID().replaceAll('-','').slice(0,8)}`; }
function safeStr(v,max=300){ return String(v ?? '').trim().slice(0,max); }
function isoDate(v){ return /^\d{4}-\d{2}-\d{2}$/.test(String(v||'')) ? String(v) : ''; }
function safeIso(v){ if(!v)return ''; const d=new Date(v); return Number.isNaN(d.getTime())?'':d.toISOString(); }
function validStudentId(v){ const id=String(v||'').toLowerCase();return /^[a-z0-9_-]{2,30}$/.test(id) && !RESERVED_IDS.has(id); }

function initialStudentData(){ return {attendanceHistory:[],currentAttendance:{status:'out',recordId:'',at:''},studySessions:[],activeStudy:null,plans:{long:[],month:[],week:[],day:[]},lectures:[],examRecords:[],events:[],preferences:{weeklyStart:1},updatedAt:nowIso()}; }
function normalizeMembership(v){return v==='beta_tester'?'beta_tester':'full_member';}
function studentUser(id,displayName=DEFAULT_DISPLAY_NAMES[id]||id,membershipType='full_member'){ return {id,role:'student',displayName:safeStr(displayName,60)||DEFAULT_DISPLAY_NAMES[id]||id,membershipType:normalizeMembership(membershipType),disabled:false,data:initialStudentData()}; }
function adminUser(id=ADMIN_ID,scope='all'){ return {id,role:'admin',displayName:id===BETA_MANAGER_ID?'베타 관리자':'관리자',adminScope:scope,disabled:false}; }
function initialState(){ const users={[ADMIN_ID]:adminUser(ADMIN_ID,'all'),[BETA_MANAGER_ID]:adminUser(BETA_MANAGER_ID,'beta')}; for(const id of DEFAULT_STUDENTS)users[id]=studentUser(id,DEFAULT_DISPLAY_NAMES[id]||id,'full_member'); return {schemaVersion:8,users,globalEvents:[],adminCalendarEvents:[],adminNotifications:[],pushSubscriptions:{[ADMIN_ID]:[],[BETA_MANAGER_ID]:[]},updatedAt:nowIso()}; }

function localDateFromISO(iso){ try{const d=new Date(iso),parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(d),m=Object.fromEntries(parts.map(p=>[p.type,p.value]));return `${m.year}-${m.month}-${m.day}`}catch{return''} }
function localHM(iso){ try{return new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(iso))}catch{return''} }
function todayKST(){ return localDateFromISO(nowIso()); }

function sanitizeAttendance(input){ return (Array.isArray(input)?input:[]).slice(-3000).map(x=>({id:safeStr(x.id,80)||uid('att'),date:isoDate(x.date)||(safeIso(x.inAt)?localDateFromISO(x.inAt):''),inAt:safeIso(x.inAt),outAt:safeIso(x.outAt)||null})).filter(x=>x.date&&x.inAt); }
function sanitizeStudySessions(input){ return (Array.isArray(input)?input:[]).slice(-5000).map(x=>{const startAt=safeIso(x.startAt),endAt=safeIso(x.endAt);let seconds=Math.max(1,Number(x.seconds)||0);if(startAt&&endAt)seconds=Math.max(1,Math.floor((new Date(endAt)-new Date(startAt))/1000));return{id:safeStr(x.id,80)||uid('ses'),date:isoDate(x.date)||(startAt?localDateFromISO(startAt):''),startAt,endAt,seconds,focus:Math.max(1,Math.min(3,Number(x.focus)||2)),subject:safeStr(x.subject,60),detail:safeStr(x.detail,180),note:safeStr(x.note,300),todoId:safeStr(x.todoId,80),todoTitle:safeStr(x.todoTitle,160),planId:safeStr(x.planId,80),planTitle:safeStr(x.planTitle,160),sourceDeviceId:safeStr(x.sourceDeviceId,100)};}).filter(x=>x.startAt&&x.endAt&&x.date); }
function sanitizeActiveStudy(x){ if(!x||typeof x!=='object')return null;const startAt=safeIso(x.startAt);if(!startAt)return null;return{id:safeStr(x.id,80)||uid('run'),startAt,subject:safeStr(x.subject,60),detail:safeStr(x.detail,180),todoId:safeStr(x.todoId,80),todoTitle:safeStr(x.todoTitle,160),planId:safeStr(x.planId,80),planTitle:safeStr(x.planTitle,160),sourceDeviceId:safeStr(x.sourceDeviceId,100)}; }
function sanitizePlans(input){ const out={long:[],month:[],week:[],day:[]}; if(!input||typeof input!=='object')return out; for(const level of Object.keys(out)){const arr=Array.isArray(input[level])?input[level]:[];out[level]=arr.slice(0,1000).map(x=>({...x,id:safeStr(x.id,80)||uid(level[0]),title:safeStr(x.title,160),parentId:safeStr(x.parentId,80),parent:safeStr(x.parent,160),parentLevel:['long','month','week'].includes(x.parentLevel)?x.parentLevel:'',allocationPct:Number.isFinite(Number(x.allocationPct))?Math.max(0,Math.min(100,Number(x.allocationPct))):undefined,startDate:isoDate(x.startDate),endDate:isoDate(x.endDate),date:isoDate(x.date),goalType:safeStr(x.goalType,30),target:Number.isFinite(Number(x.target))?Math.max(0,Number(x.target)):undefined,completed:Number.isFinite(Number(x.completed))?Math.max(0,Number(x.completed)):undefined,goalTotal:Number.isFinite(Number(x.goalTotal))?Math.max(0,Number(x.goalTotal)):undefined,manualProgress:Number.isFinite(Number(x.manualProgress))?Math.max(0,Math.min(100,Number(x.manualProgress))):0,unit:safeStr(x.unit,20),subject:safeStr(x.subject,60),goalId:safeStr(x.goalId,80),carriedFrom:safeStr(x.carriedFrom,80),lectureId:safeStr(x.lectureId,80),_rev:Math.max(0,Number(x._rev)||0),updatedAt:safeIso(x.updatedAt)||''}));} return out; }
function sanitizeLectures(input){ return (Array.isArray(input)?input:[]).slice(0,200).map(x=>({id:safeStr(x.id,80)||uid('lec'),title:safeStr(x.title,160),subject:safeStr(x.subject,60),total:Math.max(1,Math.min(1000,Number(x.total)||1)),done:Math.max(0,Math.min(1000,Number(x.done)||0)),days:(Array.isArray(x.days)?x.days:[]).map(Number).filter(n=>n>=0&&n<=6).slice(0,7),time:/^\d{2}:\d{2}$/.test(String(x.time||''))?String(x.time):'20:00',startDate:isoDate(x.startDate),endDate:isoDate(x.endDate),parentPlanId:safeStr(x.parentPlanId,80)})); }
function sanitizeExamRecords(input){return (Array.isArray(input)?input:[]).slice(-300).map(x=>({id:safeStr(x?.id,80)||uid('exam'),title:safeStr(x?.title,120)||'시험',date:isoDate(x?.date),subjects:(Array.isArray(x?.subjects)?x.subjects:[]).slice(0,20).map(s=>({id:safeStr(s?.id,80)||uid('subj'),subject:safeStr(s?.subject,60),score:Number.isFinite(Number(s?.score))?Math.max(0,Number(s.score)):0,grade:safeStr(s?.grade,20),difficulty:Math.max(.5,Math.min(5,Math.round((Number(s?.difficulty)||2.5)*2)/2)),memo:safeStr(s?.memo,600)})).filter(s=>s.subject),_rev:Math.max(0,Number(x?._rev)||0),updatedAt:safeIso(x?.updatedAt)||nowIso()})).filter(x=>x.title&&x.date&&x.subjects.length)}
function deriveCurrentAttendance(history){const open=[...(history||[])].reverse().find(r=>r.inAt&&!r.outAt);return open?{status:'in',recordId:open.id,at:open.inAt}:{status:'out',recordId:'',at:''}}
function sanitizeCurrentAttendance(x,history){if(x&&x.status==='in'){const rec=(history||[]).find(r=>r.id===safeStr(x.recordId,80)&&r.inAt&&!r.outAt);if(rec)return{status:'in',recordId:rec.id,at:rec.inAt}}return deriveCurrentAttendance(history)}
function sanitizeEvent(x,createdBy){ const startDate=isoDate(x?.startDate||x?.date);let endDate=isoDate(x?.endDate)||startDate;if(startDate&&endDate<startDate)endDate=startDate;return{id:safeStr(x?.id,80)||uid('evt'),title:safeStr(x?.title,160),type:['mock','exam','performance','academy','assignment','consult','other'].includes(x?.type)?x.type:'other',subject:safeStr(x?.subject,60),importance:['normal','important','critical'].includes(x?.importance)?x.importance:'normal',startDate,endDate,note:safeStr(x?.note,500),createdBy:createdBy||safeStr(x?.createdBy,80),createdAt:safeIso(x?.createdAt)||nowIso()}; }
function sanitizeAdminEvent(x){ const startDate=isoDate(x?.startDate||x?.date);let endDate=isoDate(x?.endDate)||startDate;if(startDate&&endDate<startDate)endDate=startDate;return{id:safeStr(x?.id,80)||uid('aevt'),title:safeStr(x?.title,160),importance:['normal','important','critical'].includes(x?.importance)?x.importance:'normal',startDate,endDate,time:/^\d{2}:\d{2}$/.test(String(x?.time||''))?String(x.time):'',note:safeStr(x?.note,500),reminderAt:safeIso(x?.reminderAt)||'',reminderSentAt:safeIso(x?.reminderSentAt)||'',createdAt:safeIso(x?.createdAt)||nowIso(),updatedAt:nowIso()}; }
function normalizeStudentData(d){d=d&&typeof d==='object'?d:{};const attendanceHistory=sanitizeAttendance(d.attendanceHistory);return{attendanceHistory,currentAttendance:sanitizeCurrentAttendance(d.currentAttendance,attendanceHistory),studySessions:sanitizeStudySessions(d.studySessions),activeStudy:sanitizeActiveStudy(d.activeStudy),plans:sanitizePlans(d.plans),lectures:sanitizeLectures(d.lectures),examRecords:sanitizeExamRecords(d.examRecords),events:(Array.isArray(d.events)?d.events:[]).slice(0,1000).map(x=>sanitizeEvent(x,safeStr(x.createdBy,80))).filter(e=>e.title&&e.startDate),preferences:{weeklyStart:1,...(d.preferences||{})},updatedAt:safeIso(d.updatedAt)||nowIso()}; }
function normalizeImportedState(parsed){
 const st=initialState();parsed=parsed&&typeof parsed==='object'?parsed:{};st.schemaVersion=8;
 st.users={[ADMIN_ID]:adminUser(ADMIN_ID,'all'),[BETA_MANAGER_ID]:adminUser(BETA_MANAGER_ID,'beta')};
 const parsedUsers=parsed.users&&typeof parsed.users==='object'?parsed.users:{};
 for(const [rawId,u] of Object.entries(parsedUsers)){
  const id=safeStr(rawId,40).toLowerCase();
  if(RESERVED_IDS.has(id))continue;
  if(!validStudentId(id)||u?.role!=='student')continue;
  const importedName=safeStr(u.displayName,60)||id;
  st.users[id]={id,role:'student',displayName:(DEFAULT_DISPLAY_NAMES[id]&&importedName===id)?DEFAULT_DISPLAY_NAMES[id]:importedName,membershipType:normalizeMembership(u.membershipType||u.membership_type),disabled:!!u.disabled,createdAt:safeIso(u.createdAt)||nowIso(),deletedAt:safeIso(u.deletedAt)||'',data:normalizeStudentData(u.data)};
 }
 for(const id of DEFAULT_STUDENTS)if(!st.users[id])st.users[id]=studentUser(id,DEFAULT_DISPLAY_NAMES[id]||id,'full_member');
 st.globalEvents=(Array.isArray(parsed.globalEvents)?parsed.globalEvents:[]).map(x=>sanitizeEvent(x,safeStr(x.createdBy,80))).filter(e=>e.title&&e.startDate);
 st.adminCalendarEvents=(Array.isArray(parsed.adminCalendarEvents)?parsed.adminCalendarEvents:[]).map(sanitizeAdminEvent).filter(e=>e.title&&e.startDate);
 st.adminNotifications=Array.isArray(parsed.adminNotifications)?parsed.adminNotifications.slice(0,1000):[];
 st.pushSubscriptions=parsed.pushSubscriptions&&typeof parsed.pushSubscriptions==='object'?parsed.pushSubscriptions:{[ADMIN_ID]:[],[BETA_MANAGER_ID]:[]};
 if(!Array.isArray(st.pushSubscriptions[ADMIN_ID]))st.pushSubscriptions[ADMIN_ID]=[];
 if(!Array.isArray(st.pushSubscriptions[BETA_MANAGER_ID]))st.pushSubscriptions[BETA_MANAGER_ID]=[];
 st.updatedAt=safeIso(parsed.updatedAt)||nowIso();return st;
}

async function ensureDb(env){
 if(schemaReady)return;if(!env.DB)throw new Error('D1 binding DB is missing');
 await env.DB.batch([
  env.DB.prepare(`CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, role TEXT NOT NULL, display_name TEXT NOT NULL, disabled INTEGER NOT NULL DEFAULT 0, created_at TEXT, deleted_at TEXT, data_json TEXT, membership_type TEXT NOT NULL DEFAULT 'full_member', admin_scope TEXT NOT NULL DEFAULT '', data_version INTEGER NOT NULL DEFAULT 0)`),
  env.DB.prepare(`CREATE TABLE IF NOT EXISTS app_kv (key TEXT PRIMARY KEY, value_json TEXT NOT NULL, updated_at TEXT NOT NULL)`),
  env.DB.prepare(`CREATE TABLE IF NOT EXISTS sessions (token TEXT PRIMARY KEY, user_id TEXT NOT NULL, expires_at INTEGER NOT NULL)`),
  env.DB.prepare(`CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id)`),
  env.DB.prepare(`CREATE TABLE IF NOT EXISTS student_devices (user_id TEXT NOT NULL, device_id TEXT NOT NULL, last_seen_at TEXT NOT NULL, last_sync_at TEXT NOT NULL, PRIMARY KEY(user_id,device_id))`),
  env.DB.prepare(`CREATE TABLE IF NOT EXISTS mutation_log (user_id TEXT NOT NULL, mutation_id TEXT NOT NULL, created_at TEXT NOT NULL, PRIMARY KEY(user_id,mutation_id))`)
 ]);
 const cols=await env.DB.prepare(`PRAGMA table_info(users)`).all(),names=new Set((cols.results||[]).map(x=>x.name));
 if(!names.has('membership_type'))await env.DB.prepare(`ALTER TABLE users ADD COLUMN membership_type TEXT NOT NULL DEFAULT 'full_member'`).run();
 if(!names.has('admin_scope'))await env.DB.prepare(`ALTER TABLE users ADD COLUMN admin_scope TEXT NOT NULL DEFAULT ''`).run();
 if(!names.has('data_version'))await env.DB.prepare(`ALTER TABLE users ADD COLUMN data_version INTEGER NOT NULL DEFAULT 0`).run();
 const count=await env.DB.prepare(`SELECT COUNT(*) AS c FROM users`).first();
 if(!count||Number(count.c)===0)await importState(env,initialState());
 else{
  await env.DB.prepare(`UPDATE users SET membership_type='full_member' WHERE role='student' AND (membership_type IS NULL OR membership_type NOT IN ('full_member','beta_tester'))`).run();
  await saveUser(env,adminUser(ADMIN_ID,'all'));
  await saveUser(env,adminUser(BETA_MANAGER_ID,'beta'));
 }
 schemaReady=true;
}

async function loadState(env){
 await ensureDb(env);
 const usersRes=await env.DB.prepare(`SELECT id,role,display_name,disabled,created_at,deleted_at,data_json,membership_type,admin_scope,data_version FROM users`).all();
 const kvRes=await env.DB.prepare(`SELECT key,value_json FROM app_kv`).all();
 const st=initialState();st.users={};
 for(const r of usersRes.results||[]){
  if(r.role==='admin'){st.users[r.id]={id:r.id,role:'admin',displayName:r.display_name||(r.id===BETA_MANAGER_ID?'베타 관리자':'관리자'),adminScope:r.id===BETA_MANAGER_ID?'beta':(r.admin_scope||'all'),disabled:!!r.disabled};continue}
  if(r.role!=='student')continue;
  st.users[r.id]={id:r.id,role:'student',displayName:r.display_name||r.id,membershipType:normalizeMembership(r.membership_type),disabled:!!r.disabled,createdAt:r.created_at||'',deletedAt:r.deleted_at||'',data:normalizeStudentData(parseJson(r.data_json,{})),dataVersion:Number(r.data_version||0)};
 }
 if(!st.users[ADMIN_ID])st.users[ADMIN_ID]=adminUser(ADMIN_ID,'all');
 if(!st.users[BETA_MANAGER_ID])st.users[BETA_MANAGER_ID]=adminUser(BETA_MANAGER_ID,'beta');
 for(const id of DEFAULT_STUDENTS)if(!st.users[id])st.users[id]=studentUser(id,DEFAULT_DISPLAY_NAMES[id]||id,'full_member');
 for(const [id,name] of Object.entries(DEFAULT_DISPLAY_NAMES)){const u=st.users[id];if(u&&u.role==='student'&&u.displayName===id){u.displayName=name;await env.DB.prepare(`UPDATE users SET display_name=? WHERE id=?`).bind(name,id).run();}}
 const kv=Object.fromEntries((kvRes.results||[]).map(r=>[r.key,parseJson(r.value_json,null)]));
 st.schemaVersion=8;st.globalEvents=Array.isArray(kv.globalEvents)?kv.globalEvents:[];st.adminCalendarEvents=Array.isArray(kv.adminCalendarEvents)?kv.adminCalendarEvents:[];st.adminNotifications=Array.isArray(kv.adminNotifications)?kv.adminNotifications:[];st.pushSubscriptions=kv.pushSubscriptions&&typeof kv.pushSubscriptions==='object'?kv.pushSubscriptions:{[ADMIN_ID]:[],[BETA_MANAGER_ID]:[]};st.updatedAt=typeof kv.updatedAt==='string'?kv.updatedAt:nowIso();return st;
}
function parseJson(v,fallback){try{return JSON.parse(v)}catch{return fallback}}
async function saveUser(env,u){
 await env.DB.prepare(`INSERT INTO users(id,role,display_name,disabled,created_at,deleted_at,data_json,membership_type,admin_scope,data_version) VALUES(?,?,?,?,?,?,?,?,?,1) ON CONFLICT(id) DO UPDATE SET role=excluded.role,display_name=excluded.display_name,disabled=excluded.disabled,created_at=excluded.created_at,deleted_at=excluded.deleted_at,data_json=excluded.data_json,membership_type=excluded.membership_type,admin_scope=excluded.admin_scope,data_version=users.data_version+1`).bind(u.id,u.role,u.displayName||u.id,u.disabled?1:0,u.createdAt||'',u.deletedAt||'',u.role==='student'?JSON.stringify(u.data||initialStudentData()):null,u.role==='student'?normalizeMembership(u.membershipType):'full_member',u.role==='admin'?(u.adminScope||'all'):'').run();
}
async function insertNewStudent(env,u){
 if(u.membershipType!=='beta_tester'){await saveUser(env,u);return true}
 const dataJson=JSON.stringify(u.data||initialStudentData());
 const r=await env.DB.prepare(`INSERT INTO users(id,role,display_name,disabled,created_at,deleted_at,data_json,membership_type,admin_scope,data_version) SELECT ?,?,?,?,?,?,?,?,?,1 WHERE (SELECT COUNT(*) FROM users WHERE role='student' AND membership_type='beta_tester') < ?`).bind(u.id,'student',u.displayName||u.id,0,u.createdAt||nowIso(),'',dataJson,'beta_tester','',INVITE_LIMIT).run();
 return Number(r?.meta?.changes||0)>0;
}
async function deleteAllUsers(env){ await env.DB.prepare(`DELETE FROM users`).run(); }
async function saveKv(env,key,value){ await env.DB.prepare(`INSERT INTO app_kv(key,value_json,updated_at) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET value_json=excluded.value_json,updated_at=excluded.updated_at`).bind(key,JSON.stringify(value),nowIso()).run(); }
async function touch(env,state){ state.updatedAt=nowIso();await saveKv(env,'updatedAt',state.updatedAt); }
async function importState(env,input){
 const st=normalizeImportedState(input);await env.DB.prepare(`DELETE FROM users`).run();const stmts=[];
 for(const u of Object.values(st.users)){stmts.push(env.DB.prepare(`INSERT INTO users(id,role,display_name,disabled,created_at,deleted_at,data_json,membership_type,admin_scope,data_version) VALUES(?,?,?,?,?,?,?,?,?,1)`).bind(u.id,u.role,u.displayName||u.id,u.disabled?1:0,u.createdAt||'',u.deletedAt||'',u.role==='student'?JSON.stringify(u.data||initialStudentData()):null,u.role==='student'?normalizeMembership(u.membershipType):'full_member',u.role==='admin'?(u.adminScope||'all'):''));}
 stmts.push(env.DB.prepare(`INSERT OR REPLACE INTO app_kv(key,value_json,updated_at) VALUES('globalEvents',?,?)`).bind(JSON.stringify(st.globalEvents),nowIso()));
 stmts.push(env.DB.prepare(`INSERT OR REPLACE INTO app_kv(key,value_json,updated_at) VALUES('adminCalendarEvents',?,?)`).bind(JSON.stringify(st.adminCalendarEvents),nowIso()));
 stmts.push(env.DB.prepare(`INSERT OR REPLACE INTO app_kv(key,value_json,updated_at) VALUES('adminNotifications',?,?)`).bind(JSON.stringify(st.adminNotifications),nowIso()));
 stmts.push(env.DB.prepare(`INSERT OR REPLACE INTO app_kv(key,value_json,updated_at) VALUES('pushSubscriptions',?,?)`).bind(JSON.stringify(st.pushSubscriptions),nowIso()));
 stmts.push(env.DB.prepare(`INSERT OR REPLACE INTO app_kv(key,value_json,updated_at) VALUES('updatedAt',?,?)`).bind(JSON.stringify(st.updatedAt),nowIso()));
 await env.DB.batch(stmts);return st;
}

function publicUser(u){if(!u)return null;const base={id:u.id,role:u.role,displayName:u.displayName};if(u.role==='student')base.membershipType=normalizeMembership(u.membershipType);if(u.role==='admin')base.adminScope=u.adminScope||'all';return base}
function activeUser(state,id){const u=state.users[id];return u&&!u.disabled?u:null}
function parseCookies(req){const out={};String(req.headers.get('cookie')||'').split(';').forEach(part=>{const i=part.indexOf('=');if(i<0)return;out[part.slice(0,i).trim()]=decodeURIComponent(part.slice(i+1).trim())});return out}
function randomToken(){const bytes=new Uint8Array(32);crypto.getRandomValues(bytes);return btoa(String.fromCharCode(...bytes)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')}
async function auth(req,env,state){const token=parseCookies(req).sf_session;if(!token)return null;const row=await env.DB.prepare(`SELECT user_id,expires_at FROM sessions WHERE token=?`).bind(token).first();if(!row)return null;if(Number(row.expires_at)<Date.now()){await env.DB.prepare(`DELETE FROM sessions WHERE token=?`).bind(token).run();return null}const u=activeUser(state,row.user_id);return publicUser(u)}
async function newSession(env,user){const token=randomToken(),exp=Date.now()+1000*60*60*24*30;await env.DB.prepare(`DELETE FROM sessions WHERE expires_at<?`).bind(Date.now()).run();await env.DB.prepare(`INSERT INTO sessions(token,user_id,expires_at) VALUES(?,?,?)`).bind(token,user.id,exp).run();return{token,exp}}
function sessionCookie(token,maxAge=2592000){return `sf_session=${encodeURIComponent(token)}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${maxAge}; Secure`}

function headers(extra={}){return{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...extra}}
function json(obj,status=200,extra={}){return new Response(JSON.stringify(obj),{status,headers:headers({'Content-Type':'application/json; charset=utf-8',...extra})})}
async function readBody(req,limit=1024*1024){const text=await req.text();if(text.length>limit)throw new Error('too_large');if(!text)return{};try{return JSON.parse(text)}catch{throw new Error('bad_json')}}

function canAdminAccessStudent(admin,stu){return !!admin&&admin.role==='admin'&&!!stu&&stu.role==='student'&&(admin.adminScope!=='beta'||stu.membershipType==='beta_tester')}
function studentIds(state,admin=null){return Object.values(state.users).filter(u=>u.role==='student'&&!u.disabled&&(!admin||canAdminAccessStudent(admin,u))).map(u=>u.id).sort()}
function scopedNotifications(state,admin){if(!admin||admin.adminScope!=='beta')return state.adminNotifications;return state.adminNotifications.filter(n=>{const stu=state.users[n.studentId];return stu&&stu.role==='student'&&stu.membershipType==='beta_tester'})}
function membershipCounts(state){const all=Object.values(state.users).filter(u=>u.role==='student');return{full:all.filter(u=>u.membershipType!=='beta_tester'&&!u.disabled).length,beta:all.filter(u=>u.membershipType==='beta_tester'&&!u.disabled).length,betaUsed:all.filter(u=>u.membershipType==='beta_tester').length,betaLimit:INVITE_LIMIT}}
function studentPayload(state,id,dataOverride=null,extra={}){const u=activeUser(state,id);return{profile:publicUser(u),data:dataOverride||u.data,globalEvents:state.globalEvents,serverNow:nowIso(),...extra}}
function dayProgress(p){if(p.goalType==='check')return Number(p.completed||0)>=1?100:0;const t=Number(p.target||0),c=Number(p.completed||0);return t>0?Math.min(100,Math.round(c/t*100)):0}
function todayPlanProgress(data,date=todayKST()){const list=data.plans.day.filter(p=>p.date===date);return list.length?Math.round(list.reduce((a,p)=>a+dayProgress(p),0)/list.length):0}
function studySecondsOn(data,date=todayKST()){return data.studySessions.filter(s=>s.date===date).reduce((a,s)=>a+Math.max(0,Number(s.seconds)||0),0)+(data.activeStudy&&localDateFromISO(data.activeStudy.startAt)===date?Math.floor((Date.now()-new Date(data.activeStudy.startAt).getTime())/1000):0)}
function attendanceSummary(data,date=todayKST()){const recs=data.attendanceHistory.filter(r=>r.date===date),live=data.currentAttendance?.status==='in'?data.attendanceHistory.find(r=>r.id===data.currentAttendance.recordId&&!r.outAt):null,open=live&&live.date===date?live:[...recs].reverse().find(r=>r.inAt&&!r.outAt);return{records:recs,checkedIn:!!open,current:open||null,firstIn:recs[0]?.inAt||null,lastOut:[...recs].reverse().find(r=>r.outAt)?.outAt||null}}
function adminOverview(state,admin){const date=todayKST(),now=Date.now();return studentIds(state,admin).map(id=>{const u=state.users[id],d=u.data,a=attendanceSummary(d,date),studySeconds=studySecondsOn(d,date),todayPlans=d.plans.day.filter(p=>p.date===date),todoDone=todayPlans.filter(p=>dayProgress(p)>=100).length,issues=[];if(d.activeStudy){const sec=Math.max(0,Math.floor((now-new Date(d.activeStudy.startAt).getTime())/1000));if(sec>=4*3600)issues.push({type:'long_timer',detail:`${Math.floor(sec/3600)}시간 ${Math.floor(sec%3600/60)}분째 진행 중`})}const oldOpen=[...d.attendanceHistory].reverse().find(r=>r.inAt&&!r.outAt&&r.date<date);if(oldOpen)issues.push({type:'old_checkin',detail:`${oldOpen.date} 입실 기록`});if(a.checkedIn&&a.current?.inAt){const since=Math.max(0,(now-new Date(a.current.inAt).getTime())/1000);if(since>=2*3600&&studySeconds<10*60)issues.push({type:'no_study_after_checkin',detail:`입실 ${Math.floor(since/3600)}시간 경과`})}const suspicious=(d.studySessions||[]).filter(s=>s.date===date&&Number(s.seconds||0)>=6*3600);if(suspicious.length)issues.push({type:'long_session',detail:`6시간 이상 기록 ${suspicious.length}건`});return{id,displayName:u.displayName,membershipType:normalizeMembership(u.membershipType),attendance:a,activeStudy:d.activeStudy,currentStudyLabel:d.activeStudy?.todoTitle||'미기록 플랜',studySeconds,planProgress:todayPlanProgress(d,date),todayPlans:todayPlans.length,todoTotal:todayPlans.length,todoDone,issues,updatedAt:d.updatedAt}})}
async function addAdminNotification(env,state,studentId,kind,title,body){const n={id:uid('noti'),studentId,kind,title,body,createdAt:nowIso(),read:false};state.adminNotifications.unshift(n);state.adminNotifications=state.adminNotifications.slice(0,1000);await saveKv(env,'adminNotifications',state.adminNotifications);return n}
async function checkAdminReminders(env,state){const now=Date.now();let changed=false;for(const e of state.adminCalendarEvents){if(!e.reminderAt||e.reminderSentAt)continue;const t=new Date(e.reminderAt).getTime();if(Number.isNaN(t)||t>now)continue;e.reminderSentAt=nowIso();state.adminNotifications.unshift({id:uid('noti'),studentId:'',kind:'admin_reminder',title:'STEPFLOW 일정 알림',body:`${e.title}${e.time?` · ${e.time}`:''}`,createdAt:nowIso(),read:false});changed=true}if(changed){state.adminNotifications=state.adminNotifications.slice(0,1000);await saveKv(env,'adminCalendarEvents',state.adminCalendarEvents);await saveKv(env,'adminNotifications',state.adminNotifications)}return changed}

function requestDeviceId(req){const v=safeStr(req.headers.get('x-stepflow-device-id'),100);return /^[A-Za-z0-9_-]{8,100}$/.test(v)?v:''}
function requestMutationId(req){const v=safeStr(req.headers.get('x-stepflow-mutation-id'),120);return /^[A-Za-z0-9_-]{8,120}$/.test(v)?v:''}
async function touchDevice(env,userId,deviceId,sync=true){if(!deviceId)return;const n=nowIso();await env.DB.prepare(`INSERT INTO student_devices(user_id,device_id,last_seen_at,last_sync_at) VALUES(?,?,?,?) ON CONFLICT(user_id,device_id) DO UPDATE SET last_seen_at=excluded.last_seen_at,last_sync_at=CASE WHEN ? THEN excluded.last_sync_at ELSE student_devices.last_sync_at END`).bind(userId,deviceId,n,sync?n:'',sync?1:0).run()}
async function deviceStatus(env,userId){const r=await env.DB.prepare(`SELECT COUNT(*) AS c, MAX(last_sync_at) AS last_sync_at, MAX(last_seen_at) AS last_seen_at FROM student_devices WHERE user_id=?`).bind(userId).first();return{deviceCount:Number(r?.c||0),lastSyncAt:r?.last_sync_at||'',lastSeenAt:r?.last_seen_at||''}}
async function mutationSeen(env,userId,mutationId){if(!mutationId)return false;const r=await env.DB.prepare(`SELECT 1 AS ok FROM mutation_log WHERE user_id=? AND mutation_id=?`).bind(userId,mutationId).first();return !!r}
async function rememberMutation(env,userId,mutationId){if(!mutationId)return;await env.DB.prepare(`INSERT OR IGNORE INTO mutation_log(user_id,mutation_id,created_at) VALUES(?,?,?)`).bind(userId,mutationId,nowIso()).run();await env.DB.prepare(`DELETE FROM mutation_log WHERE created_at < ?`).bind(new Date(Date.now()-1000*60*60*24*45).toISOString()).run()}
async function loadStudentDirect(env,id){const r=await env.DB.prepare(`SELECT id,role,display_name,disabled,created_at,deleted_at,data_json,membership_type,data_version FROM users WHERE id=?`).bind(id).first();if(!r||r.role!=='student'||r.disabled)return null;return{id:r.id,role:'student',displayName:r.display_name||r.id,membershipType:normalizeMembership(r.membership_type),disabled:!!r.disabled,createdAt:r.created_at||'',deletedAt:r.deleted_at||'',data:normalizeStudentData(parseJson(r.data_json,{})),dataVersion:Number(r.data_version||0)}}
async function mutateStudentData(env,id,mutator){for(let attempt=0;attempt<6;attempt++){const stu=await loadStudentDirect(env,id);if(!stu)throw new Error('student_not_found');const d=cloneServer(stu.data),result=await mutator(d,stu);d.currentAttendance=sanitizeCurrentAttendance(d.currentAttendance,d.attendanceHistory);d.updatedAt=nowIso();const r=await env.DB.prepare(`UPDATE users SET data_json=?, data_version=data_version+1 WHERE id=? AND data_version=?`).bind(JSON.stringify(normalizeStudentData(d)),id,stu.dataVersion).run();if(Number(r?.meta?.changes||0)>0)return{stu:{...stu,data:normalizeStudentData(d),dataVersion:stu.dataVersion+1},result}}throw new Error('concurrent_update')}
function cloneServer(v){return JSON.parse(JSON.stringify(v))}
function planEntityMap(plans){const m=new Map();for(const level of ['long','month','week','day'])for(const item of plans?.[level]||[])m.set(`${level}:${item.id}`,{level,item});return m}
function lectureMap(arr){return new Map((arr||[]).map(x=>[x.id,x]))}
async function requireRole(req,env,state,role){const u=await auth(req,env,state);if(!u)return{error:json({error:'login_required'},401)};if(u.role!==role)return{error:json({error:'forbidden'},403)};return{user:u}}

async function handleApi(req,env){await ensureDb(env);const url=new URL(req.url),p=url.pathname,state=await loadState(env);await checkAdminReminders(env,state);
 if(p==='/api/login'&&req.method==='POST'){const b=await readBody(req),id=safeStr(b.id,40).toLowerCase(),u=activeUser(state,id);if(!u)return json({error:'invalid_id'},401);const pu=publicUser(u),ses=await newSession(env,pu);return json({user:pu},200,{'Set-Cookie':sessionCookie(ses.token)})}
 if(p==='/api/register'&&req.method==='POST'){const b=await readBody(req),code=safeStr(b.inviteCode,60),id=safeStr(b.id,40).toLowerCase(),displayName=safeStr(b.displayName,60);if(code!==INVITE_CODE)return json({error:'invalid_invite'},403);if(!displayName)return json({error:'missing_name'},400);if(!validStudentId(id))return json({error:'bad_id'},400);if(state.users[id])return json({error:'already_exists'},409);const stu={...studentUser(id,displayName,'beta_tester'),createdAt:nowIso()};let ok=false;try{ok=await insertNewStudent(env,stu)}catch(e){if(String(e?.message||'').includes('UNIQUE'))return json({error:'already_exists'},409);throw e}if(!ok)return json({error:'beta_full'},409);await touch(env,state);const pu=publicUser(stu),ses=await newSession(env,pu),counts=await env.DB.prepare(`SELECT COUNT(*) AS c FROM users WHERE role='student' AND membership_type='beta_tester'`).first();return json({user:pu,betaUsed:Number(counts?.c||0),betaLimit:INVITE_LIMIT},201,{'Set-Cookie':sessionCookie(ses.token)})}
 if(p==='/api/logout'&&req.method==='POST'){const token=parseCookies(req).sf_session;if(token)await env.DB.prepare(`DELETE FROM sessions WHERE token=?`).bind(token).run();return json({ok:true},200,{'Set-Cookie':sessionCookie('',0)})}
 if(p==='/api/session'&&req.method==='GET'){const u=await auth(req,env,state);return u?json({user:u}):json({error:'login_required'},401)}

 if(p==='/api/me'&&req.method==='GET'){const a=await requireRole(req,env,state,'student');if(a.error)return a.error;const deviceId=requestDeviceId(req);await touchDevice(env,a.user.id,deviceId,true);const fresh=await loadStudentDirect(env,a.user.id);return json(studentPayload(state,a.user.id,fresh?.data||state.users[a.user.id].data,{syncStatus:await deviceStatus(env,a.user.id)}))}
 if(p==='/api/plans/sync'&&req.method==='POST'){const a=await requireRole(req,env,state,'student');if(a.error)return a.error;const b=await readBody(req,2*1024*1024),changes=Array.isArray(b.changes)?b.changes.slice(0,500):[],deviceId=requestDeviceId(req),mutationId=requestMutationId(req);if(await mutationSeen(env,a.user.id,mutationId)){const fresh=await loadStudentDirect(env,a.user.id);return json(studentPayload(state,a.user.id,fresh.data,{syncStatus:await deviceStatus(env,a.user.id)}))}try{const out=await mutateStudentData(env,a.user.id,(d)=>{const conflicts=[];for(const ch of changes){const level=['long','month','week','day'].includes(ch.level)?ch.level:'';if(!level)continue;const arr=d.plans[level],id=safeStr(ch.id||ch.item?.id,80);if(!id)continue;const idx=arr.findIndex(x=>x.id===id),cur=idx>=0?arr[idx]:null,curRev=Math.max(0,Number(cur?._rev)||0),baseRev=Math.max(0,Number(ch.baseRev)||0);if(curRev!==baseRev){conflicts.push({level,id,current:cur});continue}if(ch.op==='delete'){if(idx>=0)arr.splice(idx,1);continue}if(ch.op==='upsert'&&ch.item){const item=sanitizePlans({[level]:[{...ch.item,id}]})[level][0];if(!item)continue;item._rev=curRev+1;item.updatedAt=nowIso();if(idx>=0)arr[idx]=item;else arr.push(item)}}if(conflicts.length){const e=new Error('sync_conflict');e.conflicts=conflicts;throw e}return{applied:changes.length}});await rememberMutation(env,a.user.id,mutationId);await touchDevice(env,a.user.id,deviceId,true);return json(studentPayload(state,a.user.id,out.stu.data,{syncStatus:await deviceStatus(env,a.user.id)}))}catch(e){if(e?.message==='sync_conflict'){const fresh=await loadStudentDirect(env,a.user.id);return json({error:'sync_conflict',conflicts:e.conflicts||[],...studentPayload(state,a.user.id,fresh.data,{syncStatus:await deviceStatus(env,a.user.id)})},409)}throw e}}
 if(p==='/api/plans'&&req.method==='PUT'){const a=await requireRole(req,env,state,'student');if(a.error)return a.error;const b=await readBody(req),deviceId=requestDeviceId(req);const out=await mutateStudentData(env,a.user.id,(d)=>{d.plans=sanitizePlans(b.plans);return{}});await touchDevice(env,a.user.id,deviceId,true);return json(studentPayload(state,a.user.id,out.stu.data,{syncStatus:await deviceStatus(env,a.user.id)}))}
 if(p==='/api/lectures/sync'&&req.method==='POST'){const a=await requireRole(req,env,state,'student');if(a.error)return a.error;const b=await readBody(req),changes=Array.isArray(b.changes)?b.changes.slice(0,300):[],deviceId=requestDeviceId(req),mutationId=requestMutationId(req);if(await mutationSeen(env,a.user.id,mutationId)){const fresh=await loadStudentDirect(env,a.user.id);return json(studentPayload(state,a.user.id,fresh.data,{syncStatus:await deviceStatus(env,a.user.id)}))}const out=await mutateStudentData(env,a.user.id,(d)=>{for(const ch of changes){const id=safeStr(ch.id||ch.item?.id,80);if(!id)continue;const idx=d.lectures.findIndex(x=>x.id===id);if(ch.op==='delete'){if(idx>=0)d.lectures.splice(idx,1)}else if(ch.op==='upsert'&&ch.item){const item=sanitizeLectures([{...ch.item,id}])[0];if(!item)continue;if(idx>=0)d.lectures[idx]=item;else d.lectures.push(item)}}return{}});await rememberMutation(env,a.user.id,mutationId);await touchDevice(env,a.user.id,deviceId,true);return json(studentPayload(state,a.user.id,out.stu.data,{syncStatus:await deviceStatus(env,a.user.id)}))}
 if(p==='/api/lectures'&&req.method==='PUT'){const a=await requireRole(req,env,state,'student');if(a.error)return a.error;const b=await readBody(req),out=await mutateStudentData(env,a.user.id,(d)=>{d.lectures=sanitizeLectures(b.lectures);return{}});await touchDevice(env,a.user.id,requestDeviceId(req),true);return json(studentPayload(state,a.user.id,out.stu.data,{syncStatus:await deviceStatus(env,a.user.id)}))}
 if(p==='/api/exams'&&req.method==='POST'){const a=await requireRole(req,env,state,'student');if(a.error)return a.error;const b=await readBody(req),raw=b.exam||{},deviceId=requestDeviceId(req),mutationId=requestMutationId(req);if(await mutationSeen(env,a.user.id,mutationId)){const fresh=await loadStudentDirect(env,a.user.id);return json(studentPayload(state,a.user.id,fresh.data,{syncStatus:await deviceStatus(env,a.user.id)}))}const out=await mutateStudentData(env,a.user.id,(d)=>{const exam=sanitizeExamRecords([{...raw,id:safeStr(raw.id,80)||uid('exam'),_rev:1,updatedAt:nowIso()}])[0];if(!exam)throw new Error('bad_exam');if(!d.examRecords.some(x=>x.id===exam.id))d.examRecords.push(exam);return{}});await rememberMutation(env,a.user.id,mutationId);await touchDevice(env,a.user.id,deviceId,true);return json(studentPayload(state,a.user.id,out.stu.data,{syncStatus:await deviceStatus(env,a.user.id)}))}
 if(p.startsWith('/api/exams/')&&req.method==='PUT'){const a=await requireRole(req,env,state,'student');if(a.error)return a.error;const id=decodeURIComponent(p.slice('/api/exams/'.length)),b=await readBody(req),deviceId=requestDeviceId(req),mutationId=requestMutationId(req);if(await mutationSeen(env,a.user.id,mutationId)){const fresh=await loadStudentDirect(env,a.user.id);return json(studentPayload(state,a.user.id,fresh.data,{syncStatus:await deviceStatus(env,a.user.id)}))}try{const out=await mutateStudentData(env,a.user.id,(d)=>{const idx=d.examRecords.findIndex(x=>x.id===id);if(idx<0)throw new Error('not_found');const cur=d.examRecords[idx],baseRev=Math.max(0,Number(b.baseRev??cur._rev)||0);if(Math.max(0,Number(cur._rev)||0)!==baseRev){const e=new Error('sync_conflict');e.current=cur;throw e}const exam=sanitizeExamRecords([{...(b.exam||{}),id,_rev:baseRev+1,updatedAt:nowIso()}])[0];if(!exam)throw new Error('bad_exam');d.examRecords[idx]=exam;return{}});await rememberMutation(env,a.user.id,mutationId);await touchDevice(env,a.user.id,deviceId,true);return json(studentPayload(state,a.user.id,out.stu.data,{syncStatus:await deviceStatus(env,a.user.id)}))}catch(e){if(e?.message==='sync_conflict'){const fresh=await loadStudentDirect(env,a.user.id);return json({error:'sync_conflict',current:e.current,...studentPayload(state,a.user.id,fresh.data,{syncStatus:await deviceStatus(env,a.user.id)})},409)}if(e?.message==='not_found')return json({error:'not_found'},404);throw e}}
 if(p.startsWith('/api/exams/')&&req.method==='DELETE'){const a=await requireRole(req,env,state,'student');if(a.error)return a.error;const id=decodeURIComponent(p.slice('/api/exams/'.length)),mutationId=requestMutationId(req);if(await mutationSeen(env,a.user.id,mutationId)){const fresh=await loadStudentDirect(env,a.user.id);return json(studentPayload(state,a.user.id,fresh.data,{syncStatus:await deviceStatus(env,a.user.id)}))}const out=await mutateStudentData(env,a.user.id,(d)=>{d.examRecords=d.examRecords.filter(x=>x.id!==id);return{}});await rememberMutation(env,a.user.id,mutationId);await touchDevice(env,a.user.id,requestDeviceId(req),true);return json(studentPayload(state,a.user.id,out.stu.data,{syncStatus:await deviceStatus(env,a.user.id)}))}
 if(p==='/api/attendance'&&req.method==='POST'){const a=await requireRole(req,env,state,'student');if(a.error)return a.error;const b=await readBody(req),at=safeIso(b.at)||nowIso(),date=localDateFromISO(at)||todayKST(),clientId=safeStr(b.id,80),deviceId=requestDeviceId(req),mutationId=requestMutationId(req);if(await mutationSeen(env,a.user.id,mutationId)){const fresh=await loadStudentDirect(env,a.user.id);return json(studentPayload(state,a.user.id,fresh.data,{syncStatus:await deviceStatus(env,a.user.id)}))}let notify=null;const out=await mutateStudentData(env,a.user.id,(d)=>{if(b.action==='in'){const existing=clientId?d.attendanceHistory.find(r=>r.id===clientId):null,open=d.attendanceHistory.find(r=>!r.outAt);if(!existing&&!open){const rec={id:clientId||uid('att'),date,inAt:at,outAt:null};d.attendanceHistory.push(rec);d.currentAttendance={status:'in',recordId:rec.id,at};notify=['attendance_in','입실 알림',`${a.user.displayName} 학생이 ${localHM(at)} 입실했습니다.`]}}else if(b.action==='out'){let open=clientId?d.attendanceHistory.find(r=>r.id===clientId&&!r.outAt):null;if(!open)open=[...d.attendanceHistory].reverse().find(r=>!r.outAt);if(!open){const done=clientId?d.attendanceHistory.find(r=>r.id===clientId&&r.outAt):null;if(done)return{};const e=new Error('not_checked_in');throw e}open.outAt=at;d.currentAttendance={status:'out',recordId:'',at};notify=['attendance_out','퇴실 알림',`${a.user.displayName} 학생이 ${localHM(at)} 퇴실했습니다.`]}else throw new Error('bad_action');return{}});if(notify)await addAdminNotification(env,state,a.user.id,...notify);await rememberMutation(env,a.user.id,mutationId);await touchDevice(env,a.user.id,deviceId,true);return json(studentPayload(state,a.user.id,out.stu.data,{syncStatus:await deviceStatus(env,a.user.id)}))}
 if(p==='/api/study/start'&&req.method==='POST'){const a=await requireRole(req,env,state,'student');if(a.error)return a.error;const b=await readBody(req),runId=safeStr(b.id,80)||uid('run'),deviceId=requestDeviceId(req),mutationId=requestMutationId(req);if(await mutationSeen(env,a.user.id,mutationId)){const fresh=await loadStudentDirect(env,a.user.id);return json(studentPayload(state,a.user.id,fresh.data,{syncStatus:await deviceStatus(env,a.user.id)}))}try{const out=await mutateStudentData(env,a.user.id,(d)=>{if(d.activeStudy){if(d.activeStudy.id===runId)return{};const e=new Error('already_running');e.activeStudy=d.activeStudy;throw e}const todoId=safeStr(b.todoId,80),todo=todoId?d.plans.day.find(x=>x.id===todoId):null;if(todoId&&!todo)throw new Error('todo_not_found');d.activeStudy={id:runId,startAt:safeIso(b.startAt)||nowIso(),todoId:todo?.id||'',todoTitle:todo?.title||'',planId:todo?.parentId||'',planTitle:todo?.parent||'',subject:safeStr(todo?.subject,60),sourceDeviceId:deviceId};return{}});await rememberMutation(env,a.user.id,mutationId);await touchDevice(env,a.user.id,deviceId,true);return json(studentPayload(state,a.user.id,out.stu.data,{syncStatus:await deviceStatus(env,a.user.id)}))}catch(e){if(e?.message==='already_running'){const fresh=await loadStudentDirect(env,a.user.id);return json({error:'already_running',activeStudy:e.activeStudy,...studentPayload(state,a.user.id,fresh.data,{syncStatus:await deviceStatus(env,a.user.id)})},409)}if(e?.message==='todo_not_found')return json({error:'todo_not_found'},404);throw e}}
 if(p==='/api/study/assign'&&req.method==='POST'){const a=await requireRole(req,env,state,'student');if(a.error)return a.error;const b=await readBody(req),deviceId=requestDeviceId(req),mutationId=requestMutationId(req);const out=await mutateStudentData(env,a.user.id,(d)=>{const run=d.activeStudy;if(!run)throw new Error('not_running');if(b.runId&&safeStr(b.runId,80)!==run.id)throw new Error('run_mismatch');const todoId=safeStr(b.todoId,80),todo=todoId?d.plans.day.find(x=>x.id===todoId):null;if(todoId&&!todo)throw new Error('todo_not_found');run.todoId=todo?.id||'';run.todoTitle=todo?.title||'';run.planId=todo?.parentId||'';run.planTitle=todo?.parent||'';run.subject=safeStr(todo?.subject,60);return{}});await rememberMutation(env,a.user.id,mutationId);await touchDevice(env,a.user.id,deviceId,true);return json(studentPayload(state,a.user.id,out.stu.data,{syncStatus:await deviceStatus(env,a.user.id)}))}
 if(p==='/api/study/finish'&&req.method==='POST'){const a=await requireRole(req,env,state,'student');if(a.error)return a.error;const b=await readBody(req),sessionId=safeStr(b.sessionId,80)||uid('ses'),deviceId=requestDeviceId(req),mutationId=requestMutationId(req);const out=await mutateStudentData(env,a.user.id,(d)=>{const existing=d.studySessions.find(x=>x.id===sessionId);if(existing){if(d.activeStudy&&(!b.runId||d.activeStudy.id===b.runId))d.activeStudy=null;return{}}const run=d.activeStudy;if(!run)throw new Error('not_running');if(b.runId&&safeStr(b.runId,80)!==run.id)throw new Error('run_mismatch');const endAt=safeIso(b.endAt)||nowIso(),seconds=Math.max(1,Math.floor((new Date(endAt)-new Date(run.startAt))/1000));d.studySessions.push({id:sessionId,date:localDateFromISO(run.startAt),startAt:run.startAt,endAt,seconds,focus:Math.max(1,Math.min(3,Number(b.focus)||2)),subject:safeStr(run.subject,60),detail:'',note:'',todoId:safeStr(run.todoId,80),todoTitle:safeStr(run.todoTitle,160),planId:safeStr(run.planId,80),planTitle:safeStr(run.planTitle,160),sourceDeviceId:run.sourceDeviceId||deviceId});d.activeStudy=null;return{}});await rememberMutation(env,a.user.id,mutationId);await touchDevice(env,a.user.id,deviceId,true);return json(studentPayload(state,a.user.id,out.stu.data,{syncStatus:await deviceStatus(env,a.user.id)}))}
 if(p==='/api/study/session'&&req.method==='POST'){const a=await requireRole(req,env,state,'student');if(a.error)return a.error;const b=await readBody(req),deviceId=requestDeviceId(req),mutationId=requestMutationId(req);const out=await mutateStudentData(env,a.user.id,(d)=>{const s=sanitizeStudySessions([{...(b.session||{}),sourceDeviceId:deviceId}])[0];if(!s)throw new Error('bad_session');if(!d.studySessions.some(x=>x.id===s.id))d.studySessions.push(s);if(d.activeStudy?.id===b.runId)d.activeStudy=null;return{}});await rememberMutation(env,a.user.id,mutationId);await touchDevice(env,a.user.id,deviceId,true);return json(studentPayload(state,a.user.id,out.stu.data,{syncStatus:await deviceStatus(env,a.user.id)}))}
 if(p.startsWith('/api/study/')&&req.method==='PUT'){const a=await requireRole(req,env,state,'student');if(a.error)return a.error;const id=decodeURIComponent(p.slice('/api/study/'.length));if(!id||['start','finish','assign','session'].includes(id))return json({error:'not_found'},404);const b=await readBody(req),out=await mutateStudentData(env,a.user.id,(d)=>{const idx=d.studySessions.findIndex(x=>x.id===id);if(idx<0)throw new Error('not_found');const old=d.studySessions[idx],startAt=safeIso(b.startAt)||old.startAt,endAt=safeIso(b.endAt)||old.endAt;if(!startAt||!endAt||new Date(endAt)<=new Date(startAt))throw new Error('bad_time');const todoId=safeStr(b.todoId,80),todo=todoId?d.plans.day.find(x=>x.id===todoId):null,requestedPlanId=safeStr(b.planId,80),plan=requestedPlanId?[...(d.plans.long||[]),...(d.plans.month||[]),...(d.plans.week||[])].find(x=>x.id===requestedPlanId):null;if(todoId&&!todo)throw new Error('todo_not_found');if(requestedPlanId&&!plan)throw new Error('plan_not_found');const linkedPlanId=todo?.parentId||plan?.id||'',linkedPlanTitle=todo?.parent||plan?.title||'';d.studySessions[idx]=sanitizeStudySessions([{...old,startAt,endAt,date:localDateFromISO(startAt),focus:b.focus??old.focus,todoId:todo?.id||'',todoTitle:todo?.title||'',planId:linkedPlanId,planTitle:linkedPlanTitle,subject:todo?safeStr(todo.subject,60):plan?safeStr(plan.subject,60):safeStr(b.subject??old.subject,60)}])[0];return{}});await touchDevice(env,a.user.id,requestDeviceId(req),true);return json(studentPayload(state,a.user.id,out.stu.data,{syncStatus:await deviceStatus(env,a.user.id)}))}
 if(p.startsWith('/api/study/')&&req.method==='DELETE'){const a=await requireRole(req,env,state,'student');if(a.error)return a.error;const id=decodeURIComponent(p.slice('/api/study/'.length));if(!id||['start','finish','assign','session'].includes(id))return json({error:'not_found'},404);const out=await mutateStudentData(env,a.user.id,(d)=>{const before=d.studySessions.length;d.studySessions=d.studySessions.filter(x=>x.id!==id);if(d.studySessions.length===before)throw new Error('not_found');return{}});await touchDevice(env,a.user.id,requestDeviceId(req),true);return json(studentPayload(state,a.user.id,out.stu.data,{syncStatus:await deviceStatus(env,a.user.id)}))}
 if(p==='/api/events'&&req.method==='POST'){const a=await requireRole(req,env,state,'student');if(a.error)return a.error;const b=await readBody(req),out=await mutateStudentData(env,a.user.id,(d)=>{const ev=sanitizeEvent(b.event,a.user.id);if(!ev.title||!ev.startDate)throw new Error('missing_fields');if(!d.events.some(x=>x.id===ev.id))d.events.push(ev);return{}});await touchDevice(env,a.user.id,requestDeviceId(req),true);return json(studentPayload(state,a.user.id,out.stu.data,{syncStatus:await deviceStatus(env,a.user.id)}))}
 if(p.startsWith('/api/events/')&&req.method==='DELETE'){const a=await requireRole(req,env,state,'student');if(a.error)return a.error;const id=decodeURIComponent(p.slice('/api/events/'.length)),out=await mutateStudentData(env,a.user.id,(d)=>{d.events=d.events.filter(e=>e.id!==id);return{}});await touchDevice(env,a.user.id,requestDeviceId(req),true);return json(studentPayload(state,a.user.id,out.stu.data,{syncStatus:await deviceStatus(env,a.user.id)}))}

 if(p==='/api/admin/overview'&&req.method==='GET'){const a=await requireRole(req,env,state,'admin');if(a.error)return a.error;const rawCounts=membershipCounts(state),counts=a.user.adminScope==='beta'?{beta:rawCounts.beta,betaUsed:rawCounts.betaUsed,betaLimit:rawCounts.betaLimit}:{...rawCounts},notes=scopedNotifications(state,a.user),dev=await env.DB.prepare(`SELECT user_id,COUNT(*) AS device_count,MAX(last_sync_at) AS last_sync_at,MAX(last_seen_at) AS last_seen_at FROM student_devices GROUP BY user_id`).all(),dm=Object.fromEntries((dev.results||[]).map(r=>[r.user_id,{deviceCount:Number(r.device_count||0),lastSyncAt:r.last_sync_at||'',lastSeenAt:r.last_seen_at||''}])),students=adminOverview(state,a.user).map(x=>({...x,syncStatus:dm[x.id]||{deviceCount:0,lastSyncAt:'',lastSeenAt:''}}));return json({admin:a.user,students,notifications:notes.slice(0,100),globalEvents:a.user.adminScope==='all'?state.globalEvents:[],adminCalendarEvents:a.user.adminScope==='all'?state.adminCalendarEvents:[],membershipCounts:counts,serverNow:nowIso()})}
 if(p==='/api/admin/student'&&req.method==='GET'){const a=await requireRole(req,env,state,'admin');if(a.error)return a.error;const id=safeStr(url.searchParams.get('id'),40).toLowerCase(),stu=activeUser(state,id);if(!stu||stu.role!=='student'||!canAdminAccessStudent(a.user,stu))return json({error:'not_found'},404);const fresh=await loadStudentDirect(env,id);return json(studentPayload(state,id,fresh?.data||stu.data,{syncStatus:await deviceStatus(env,id)}))}
 if(p==='/api/admin/student'&&req.method==='POST'){const a=await requireRole(req,env,state,'admin');if(a.error)return a.error;const b=await readBody(req),id=safeStr(b.id,40).toLowerCase();if(!validStudentId(id))return json({error:'bad_id'},400);const membership=a.user.adminScope==='beta'?'beta_tester':normalizeMembership(b.membershipType);if(state.users[id]&&!state.users[id].disabled)return json({error:'already_exists'},409);if(state.users[id]?.disabled){const old=state.users[id];if(!canAdminAccessStudent(a.user,old)&&a.user.adminScope!=='all')return json({error:'forbidden'},403);old.disabled=false;old.displayName=safeStr(b.displayName,60)||id;old.data=initialStudentData();old.deletedAt='';old.membershipType=membership;await saveUser(env,old);await touch(env,state);return json({student:publicUser(old)})}const stu={...studentUser(id,safeStr(b.displayName,60)||id,membership),createdAt:nowIso()};let ok=true;if(membership==='beta_tester')ok=await insertNewStudent(env,stu);else await saveUser(env,stu);if(!ok)return json({error:'beta_full'},409);await touch(env,state);return json({student:publicUser(stu)})}
 if(p.startsWith('/api/admin/student/')&&req.method==='DELETE'){const a=await requireRole(req,env,state,'admin');if(a.error)return a.error;const id=safeStr(decodeURIComponent(p.slice('/api/admin/student/'.length)),40).toLowerCase(),stu=state.users[id];if(!stu||stu.role!=='student'||stu.disabled||!canAdminAccessStudent(a.user,stu))return json({error:'not_found'},404);stu.disabled=true;stu.deletedAt=nowIso();await saveUser(env,stu);await touch(env,state);return json({ok:true})}
 if(p==='/api/admin/student-profile'&&req.method==='PUT'){const a=await requireRole(req,env,state,'admin');if(a.error)return a.error;const id=safeStr(url.searchParams.get('id'),40).toLowerCase(),stu=activeUser(state,id);if(!stu||stu.role!=='student'||!canAdminAccessStudent(a.user,stu))return json({error:'not_found'},404);const b=await readBody(req),displayName=safeStr(b.displayName,60);if(!displayName)return json({error:'missing_name'},400);stu.displayName=displayName;if(a.user.adminScope==='all'&&b.membershipType){const next=normalizeMembership(b.membershipType);if(next==='beta_tester'&&stu.membershipType!=='beta_tester'){const c=membershipCounts(state);if(c.betaUsed>=INVITE_LIMIT)return json({error:'beta_full'},409)}stu.membershipType=next}await saveUser(env,stu);await touch(env,state);return json({student:publicUser(stu)})}
 if(p==='/api/admin/student-data'&&req.method==='PUT'){const a=await requireRole(req,env,state,'admin');if(a.error)return a.error;const id=safeStr(url.searchParams.get('id'),40).toLowerCase(),stu=activeUser(state,id);if(!stu||stu.role!=='student'||!canAdminAccessStudent(a.user,stu))return json({error:'not_found'},404);const b=await readBody(req,2*1024*1024);stu.data=normalizeStudentData(b.data);stu.data.updatedAt=nowIso();await saveUser(env,stu);await touch(env,state);return json(studentPayload(state,id))}
 if(p==='/api/admin/event'&&req.method==='POST'){const a=await requireRole(req,env,state,'admin');if(a.error)return a.error;const b=await readBody(req),target=safeStr(b.target,40),ev=sanitizeEvent(b.event,a.user.id);if(!ev.title||!ev.startDate)return json({error:'missing_fields'},400);if(target==='all'){if(a.user.adminScope!=='all')return json({error:'forbidden'},403);state.globalEvents.push(ev);await saveKv(env,'globalEvents',state.globalEvents)}else{const stu=activeUser(state,target);if(!stu||stu.role!=='student'||!canAdminAccessStudent(a.user,stu))return json({error:'bad_target'},400);stu.data.events.push(ev);await saveUser(env,stu)}await touch(env,state);return json({ok:true})}
 if(p.startsWith('/api/admin/event/')&&req.method==='DELETE'){const a=await requireRole(req,env,state,'admin');if(a.error)return a.error;const id=decodeURIComponent(p.slice('/api/admin/event/'.length)),target=safeStr(url.searchParams.get('target'),40);if(target==='all'){if(a.user.adminScope!=='all')return json({error:'forbidden'},403);state.globalEvents=state.globalEvents.filter(e=>e.id!==id);await saveKv(env,'globalEvents',state.globalEvents)}else{const stu=activeUser(state,target);if(!stu||stu.role!=='student'||!canAdminAccessStudent(a.user,stu))return json({error:'bad_target'},400);stu.data.events=stu.data.events.filter(e=>e.id!==id);await saveUser(env,stu)}await touch(env,state);return json({ok:true})}
 if(p==='/api/admin/calendar-event'&&req.method==='POST'){const a=await requireRole(req,env,state,'admin');if(a.error)return a.error;if(a.user.adminScope!=='all')return json({error:'forbidden'},403);const b=await readBody(req),ev=sanitizeAdminEvent(b.event);if(!ev.title||!ev.startDate)return json({error:'missing_fields'},400);state.adminCalendarEvents.push(ev);await saveKv(env,'adminCalendarEvents',state.adminCalendarEvents);await touch(env,state);return json({event:ev})}
 if(p.startsWith('/api/admin/calendar-event/')&&req.method==='PUT'){const a=await requireRole(req,env,state,'admin');if(a.error)return a.error;if(a.user.adminScope!=='all')return json({error:'forbidden'},403);const id=decodeURIComponent(p.slice('/api/admin/calendar-event/'.length)),idx=state.adminCalendarEvents.findIndex(e=>e.id===id);if(idx<0)return json({error:'not_found'},404);const b=await readBody(req),ev=sanitizeAdminEvent({...b.event,id,createdAt:state.adminCalendarEvents[idx].createdAt});if(!ev.title||!ev.startDate)return json({error:'missing_fields'},400);const old=state.adminCalendarEvents[idx];if(old.reminderAt===ev.reminderAt)ev.reminderSentAt=old.reminderSentAt;state.adminCalendarEvents[idx]=ev;await saveKv(env,'adminCalendarEvents',state.adminCalendarEvents);await touch(env,state);return json({event:ev})}
 if(p.startsWith('/api/admin/calendar-event/')&&req.method==='DELETE'){const a=await requireRole(req,env,state,'admin');if(a.error)return a.error;if(a.user.adminScope!=='all')return json({error:'forbidden'},403);const id=decodeURIComponent(p.slice('/api/admin/calendar-event/'.length));state.adminCalendarEvents=state.adminCalendarEvents.filter(e=>e.id!==id);await saveKv(env,'adminCalendarEvents',state.adminCalendarEvents);await touch(env,state);return json({ok:true})}
 if(p==='/api/admin/notifications/read'&&req.method==='POST'){const a=await requireRole(req,env,state,'admin');if(a.error)return a.error;if(a.user.adminScope==='all')state.adminNotifications.forEach(n=>n.read=true);else{const allowed=new Set(studentIds(state,a.user));state.adminNotifications.forEach(n=>{if(allowed.has(n.studentId))n.read=true})}await saveKv(env,'adminNotifications',state.adminNotifications);return json({ok:true})}
 if(p==='/api/admin/export-state'&&req.method==='GET'){const a=await requireRole(req,env,state,'admin');if(a.error)return a.error;if(a.user.adminScope!=='all')return json({error:'forbidden'},403);return new Response(JSON.stringify(state,null,2),{status:200,headers:headers({'Content-Type':'application/json; charset=utf-8','Content-Disposition':'attachment; filename="stepflow-state.json"'})})}
 if(p==='/api/admin/import-state'&&req.method==='POST'){const a=await requireRole(req,env,state,'admin');if(a.error)return a.error;if(a.user.adminScope!=='all')return json({error:'forbidden'},403);const body=await readBody(req,8*1024*1024),st=await importState(env,body);return json({ok:true,students:Object.values(st.users).filter(u=>u.role==='student'&&!u.disabled).length})}

 if(p==='/api/push/public-key'&&req.method==='GET'){const u=await auth(req,env,state);if(!u)return json({error:'login_required'},401);return json({available:false,publicKey:''})}
 if(p==='/api/push/subscribe'&&req.method==='POST'){const u=await auth(req,env,state);if(!u)return json({error:'login_required'},401);return json({ok:true,available:false})}
 return json({error:'not_found'},404);
}

export default {
 async fetch(request,env){try{const url=new URL(request.url);if(url.pathname.startsWith('/api/'))return await handleApi(request,env);return env.ASSETS.fetch(request)}catch(e){console.error(e);const code=e?.message||'server_error',status=code==='too_large'?413:code==='not_found'?404:code==='not_checked_in'||code==='already_running'||code==='run_mismatch'||code==='concurrent_update'?409:code==='missing_fields'||code==='bad_time'||code==='bad_action'||code==='bad_exam'||code==='bad_session'?400:400;return json({error:code},status)}},
 async scheduled(_controller,env,_ctx){try{const state=await loadState(env);await checkAdminReminders(env,state)}catch(e){console.error('scheduled reminder failed',e)}}
};
