const ADMIN_ID = 'nyj5004';
const DEFAULT_STUDENTS = ['hy', 'yjw', 'nyj'];
let schemaReady = false;

function nowIso(){ return new Date().toISOString(); }
function uid(prefix='id'){ return `${prefix}_${Date.now().toString(36)}_${crypto.randomUUID().replaceAll('-','').slice(0,8)}`; }
function safeStr(v,max=300){ return String(v ?? '').trim().slice(0,max); }
function isoDate(v){ return /^\d{4}-\d{2}-\d{2}$/.test(String(v||'')) ? String(v) : ''; }
function safeIso(v){ if(!v)return ''; const d=new Date(v); return Number.isNaN(d.getTime())?'':d.toISOString(); }
function validStudentId(v){ return /^[a-z0-9_-]{2,30}$/.test(String(v||'').toLowerCase()) && String(v).toLowerCase()!==ADMIN_ID; }

function initialStudentData(){ return {attendanceHistory:[],studySessions:[],activeStudy:null,plans:{long:[],month:[],week:[],day:[]},lectures:[],events:[],preferences:{weeklyStart:1},updatedAt:nowIso()}; }
function studentUser(id,displayName=id){ return {id,role:'student',displayName:safeStr(displayName,60)||id,disabled:false,data:initialStudentData()}; }
function adminUser(){ return {id:ADMIN_ID,role:'admin',displayName:'관리자',disabled:false}; }
function initialState(){ const users={[ADMIN_ID]:adminUser()}; for(const id of DEFAULT_STUDENTS)users[id]=studentUser(id); return {schemaVersion:6,users,globalEvents:[],adminCalendarEvents:[],adminNotifications:[],pushSubscriptions:{[ADMIN_ID]:[]},updatedAt:nowIso()}; }

function localDateFromISO(iso){ try{const d=new Date(iso),parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(d),m=Object.fromEntries(parts.map(p=>[p.type,p.value]));return `${m.year}-${m.month}-${m.day}`}catch{return''} }
function localHM(iso){ try{return new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(iso))}catch{return''} }
function todayKST(){ return localDateFromISO(nowIso()); }

function sanitizeAttendance(input){ return (Array.isArray(input)?input:[]).slice(-3000).map(x=>({id:safeStr(x.id,80)||uid('att'),date:isoDate(x.date)||(safeIso(x.inAt)?localDateFromISO(x.inAt):''),inAt:safeIso(x.inAt),outAt:safeIso(x.outAt)||null})).filter(x=>x.date&&x.inAt); }
function sanitizeStudySessions(input){ return (Array.isArray(input)?input:[]).slice(-5000).map(x=>{const startAt=safeIso(x.startAt),endAt=safeIso(x.endAt);let seconds=Math.max(1,Number(x.seconds)||0);if(startAt&&endAt)seconds=Math.max(1,Math.floor((new Date(endAt)-new Date(startAt))/1000));return{id:safeStr(x.id,80)||uid('ses'),date:isoDate(x.date)||(startAt?localDateFromISO(startAt):''),startAt,endAt,seconds,focus:Math.max(1,Math.min(3,Number(x.focus)||2)),subject:safeStr(x.subject,60),detail:safeStr(x.detail,180),note:safeStr(x.note,300)};}).filter(x=>x.startAt&&x.endAt&&x.date); }
function sanitizeActiveStudy(x){ if(!x||typeof x!=='object')return null;const startAt=safeIso(x.startAt);if(!startAt)return null;return{id:safeStr(x.id,80)||uid('run'),startAt,subject:safeStr(x.subject,60),detail:safeStr(x.detail,180)}; }
function sanitizePlans(input){ const out={long:[],month:[],week:[],day:[]}; if(!input||typeof input!=='object')return out; for(const level of Object.keys(out)){const arr=Array.isArray(input[level])?input[level]:[];out[level]=arr.slice(0,1000).map(x=>({...x,id:safeStr(x.id,80)||uid(level[0]),title:safeStr(x.title,160),parentId:safeStr(x.parentId,80),parent:safeStr(x.parent,160),parentLevel:['long','month','week'].includes(x.parentLevel)?x.parentLevel:'',allocationPct:Number.isFinite(Number(x.allocationPct))?Math.max(0,Math.min(100,Number(x.allocationPct))):undefined,startDate:isoDate(x.startDate),endDate:isoDate(x.endDate),date:isoDate(x.date),goalType:safeStr(x.goalType,30),target:Number.isFinite(Number(x.target))?Math.max(0,Number(x.target)):undefined,completed:Number.isFinite(Number(x.completed))?Math.max(0,Number(x.completed)):undefined,goalTotal:Number.isFinite(Number(x.goalTotal))?Math.max(0,Number(x.goalTotal)):undefined,manualProgress:Number.isFinite(Number(x.manualProgress))?Math.max(0,Math.min(100,Number(x.manualProgress))):0,unit:safeStr(x.unit,20),subject:safeStr(x.subject,60),goalId:safeStr(x.goalId,80),carriedFrom:safeStr(x.carriedFrom,80),lectureId:safeStr(x.lectureId,80)}));} return out; }
function sanitizeLectures(input){ return (Array.isArray(input)?input:[]).slice(0,200).map(x=>({id:safeStr(x.id,80)||uid('lec'),title:safeStr(x.title,160),subject:safeStr(x.subject,60),total:Math.max(1,Math.min(1000,Number(x.total)||1)),done:Math.max(0,Math.min(1000,Number(x.done)||0)),days:(Array.isArray(x.days)?x.days:[]).map(Number).filter(n=>n>=0&&n<=6).slice(0,7),time:/^\d{2}:\d{2}$/.test(String(x.time||''))?String(x.time):'20:00',startDate:isoDate(x.startDate),endDate:isoDate(x.endDate),parentPlanId:safeStr(x.parentPlanId,80)})); }
function sanitizeEvent(x,createdBy){ const startDate=isoDate(x?.startDate||x?.date);let endDate=isoDate(x?.endDate)||startDate;if(startDate&&endDate<startDate)endDate=startDate;return{id:safeStr(x?.id,80)||uid('evt'),title:safeStr(x?.title,160),type:['mock','exam','performance','academy','assignment','consult','other'].includes(x?.type)?x.type:'other',subject:safeStr(x?.subject,60),importance:['normal','important','critical'].includes(x?.importance)?x.importance:'normal',startDate,endDate,note:safeStr(x?.note,500),createdBy:createdBy||safeStr(x?.createdBy,80),createdAt:safeIso(x?.createdAt)||nowIso()}; }
function sanitizeAdminEvent(x){ const startDate=isoDate(x?.startDate||x?.date);let endDate=isoDate(x?.endDate)||startDate;if(startDate&&endDate<startDate)endDate=startDate;return{id:safeStr(x?.id,80)||uid('aevt'),title:safeStr(x?.title,160),importance:['normal','important','critical'].includes(x?.importance)?x.importance:'normal',startDate,endDate,time:/^\d{2}:\d{2}$/.test(String(x?.time||''))?String(x.time):'',note:safeStr(x?.note,500),reminderAt:safeIso(x?.reminderAt)||'',reminderSentAt:safeIso(x?.reminderSentAt)||'',createdAt:safeIso(x?.createdAt)||nowIso(),updatedAt:nowIso()}; }
function normalizeStudentData(d){ d=d&&typeof d==='object'?d:{};return{attendanceHistory:sanitizeAttendance(d.attendanceHistory),studySessions:sanitizeStudySessions(d.studySessions),activeStudy:sanitizeActiveStudy(d.activeStudy),plans:sanitizePlans(d.plans),lectures:sanitizeLectures(d.lectures),events:(Array.isArray(d.events)?d.events:[]).slice(0,1000).map(x=>sanitizeEvent(x,safeStr(x.createdBy,80))).filter(e=>e.title&&e.startDate),preferences:{weeklyStart:1,...(d.preferences||{})},updatedAt:safeIso(d.updatedAt)||nowIso()}; }
function normalizeImportedState(parsed){ const st=initialState();parsed=parsed&&typeof parsed==='object'?parsed:{};st.schemaVersion=6;st.users={[ADMIN_ID]:adminUser()};const parsedUsers=parsed.users&&typeof parsed.users==='object'?parsed.users:{};for(const [rawId,u] of Object.entries(parsedUsers)){const id=safeStr(rawId,40).toLowerCase();if(id===ADMIN_ID&&u?.role==='admin')continue;if(!validStudentId(id)||u?.role!=='student')continue;st.users[id]={id,role:'student',displayName:safeStr(u.displayName,60)||id,disabled:!!u.disabled,createdAt:safeIso(u.createdAt)||nowIso(),deletedAt:safeIso(u.deletedAt)||'',data:normalizeStudentData(u.data)};}for(const id of DEFAULT_STUDENTS)if(!st.users[id])st.users[id]=studentUser(id);st.globalEvents=(Array.isArray(parsed.globalEvents)?parsed.globalEvents:[]).map(x=>sanitizeEvent(x,safeStr(x.createdBy,80))).filter(e=>e.title&&e.startDate);st.adminCalendarEvents=(Array.isArray(parsed.adminCalendarEvents)?parsed.adminCalendarEvents:[]).map(sanitizeAdminEvent).filter(e=>e.title&&e.startDate);st.adminNotifications=Array.isArray(parsed.adminNotifications)?parsed.adminNotifications.slice(0,1000):[];st.pushSubscriptions=parsed.pushSubscriptions&&typeof parsed.pushSubscriptions==='object'?parsed.pushSubscriptions:{[ADMIN_ID]:[]};if(!Array.isArray(st.pushSubscriptions[ADMIN_ID]))st.pushSubscriptions[ADMIN_ID]=[];st.updatedAt=safeIso(parsed.updatedAt)||nowIso();return st; }

async function ensureDb(env){ if(schemaReady)return; if(!env.DB)throw new Error('D1 binding DB is missing'); await env.DB.batch([
  env.DB.prepare(`CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, role TEXT NOT NULL, display_name TEXT NOT NULL, disabled INTEGER NOT NULL DEFAULT 0, created_at TEXT, deleted_at TEXT, data_json TEXT)`),
  env.DB.prepare(`CREATE TABLE IF NOT EXISTS app_kv (key TEXT PRIMARY KEY, value_json TEXT NOT NULL, updated_at TEXT NOT NULL)`),
  env.DB.prepare(`CREATE TABLE IF NOT EXISTS sessions (token TEXT PRIMARY KEY, user_id TEXT NOT NULL, expires_at INTEGER NOT NULL)`),
  env.DB.prepare(`CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id)`)
]);
 const count=await env.DB.prepare(`SELECT COUNT(*) AS c FROM users`).first(); if(!count||Number(count.c)===0)await importState(env,initialState()); schemaReady=true; }

async function loadState(env){ await ensureDb(env); const usersRes=await env.DB.prepare(`SELECT id,role,display_name,disabled,created_at,deleted_at,data_json FROM users`).all(); const kvRes=await env.DB.prepare(`SELECT key,value_json FROM app_kv`).all(); const st=initialState();st.users={};for(const r of usersRes.results||[]){if(r.role==='admin'){st.users[r.id]={id:r.id,role:'admin',displayName:r.display_name||'관리자',disabled:!!r.disabled};continue}if(r.role!=='student')continue;st.users[r.id]={id:r.id,role:'student',displayName:r.display_name||r.id,disabled:!!r.disabled,createdAt:r.created_at||'',deletedAt:r.deleted_at||'',data:normalizeStudentData(parseJson(r.data_json,{}))};}if(!st.users[ADMIN_ID])st.users[ADMIN_ID]=adminUser();for(const id of DEFAULT_STUDENTS)if(!st.users[id])st.users[id]=studentUser(id);const kv=Object.fromEntries((kvRes.results||[]).map(r=>[r.key,parseJson(r.value_json,null)]));st.schemaVersion=6;st.globalEvents=Array.isArray(kv.globalEvents)?kv.globalEvents:[];st.adminCalendarEvents=Array.isArray(kv.adminCalendarEvents)?kv.adminCalendarEvents:[];st.adminNotifications=Array.isArray(kv.adminNotifications)?kv.adminNotifications:[];st.pushSubscriptions=kv.pushSubscriptions&&typeof kv.pushSubscriptions==='object'?kv.pushSubscriptions:{[ADMIN_ID]:[]};st.updatedAt=typeof kv.updatedAt==='string'?kv.updatedAt:nowIso();return st; }
function parseJson(v,fallback){try{return JSON.parse(v)}catch{return fallback}}
async function saveUser(env,u){ await env.DB.prepare(`INSERT INTO users(id,role,display_name,disabled,created_at,deleted_at,data_json) VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET role=excluded.role,display_name=excluded.display_name,disabled=excluded.disabled,created_at=excluded.created_at,deleted_at=excluded.deleted_at,data_json=excluded.data_json`).bind(u.id,u.role,u.displayName||u.id,u.disabled?1:0,u.createdAt||'',u.deletedAt||'',u.role==='student'?JSON.stringify(u.data||initialStudentData()):null).run(); }
async function deleteAllUsers(env){ await env.DB.prepare(`DELETE FROM users`).run(); }
async function saveKv(env,key,value){ await env.DB.prepare(`INSERT INTO app_kv(key,value_json,updated_at) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET value_json=excluded.value_json,updated_at=excluded.updated_at`).bind(key,JSON.stringify(value),nowIso()).run(); }
async function touch(env,state){ state.updatedAt=nowIso();await saveKv(env,'updatedAt',state.updatedAt); }
async function importState(env,input){ const st=normalizeImportedState(input);await env.DB.prepare(`DELETE FROM users`).run();const stmts=[];for(const u of Object.values(st.users)){stmts.push(env.DB.prepare(`INSERT INTO users(id,role,display_name,disabled,created_at,deleted_at,data_json) VALUES(?,?,?,?,?,?,?)`).bind(u.id,u.role,u.displayName||u.id,u.disabled?1:0,u.createdAt||'',u.deletedAt||'',u.role==='student'?JSON.stringify(u.data||initialStudentData()):null));}stmts.push(env.DB.prepare(`INSERT OR REPLACE INTO app_kv(key,value_json,updated_at) VALUES('globalEvents',?,?)`).bind(JSON.stringify(st.globalEvents),nowIso()));stmts.push(env.DB.prepare(`INSERT OR REPLACE INTO app_kv(key,value_json,updated_at) VALUES('adminCalendarEvents',?,?)`).bind(JSON.stringify(st.adminCalendarEvents),nowIso()));stmts.push(env.DB.prepare(`INSERT OR REPLACE INTO app_kv(key,value_json,updated_at) VALUES('adminNotifications',?,?)`).bind(JSON.stringify(st.adminNotifications),nowIso()));stmts.push(env.DB.prepare(`INSERT OR REPLACE INTO app_kv(key,value_json,updated_at) VALUES('pushSubscriptions',?,?)`).bind(JSON.stringify(st.pushSubscriptions),nowIso()));stmts.push(env.DB.prepare(`INSERT OR REPLACE INTO app_kv(key,value_json,updated_at) VALUES('updatedAt',?,?)`).bind(JSON.stringify(st.updatedAt),nowIso()));await env.DB.batch(stmts);return st; }

function publicUser(u){return u?{id:u.id,role:u.role,displayName:u.displayName}:null}
function activeUser(state,id){const u=state.users[id];return u&&!u.disabled?u:null}
function parseCookies(req){const out={};String(req.headers.get('cookie')||'').split(';').forEach(part=>{const i=part.indexOf('=');if(i<0)return;out[part.slice(0,i).trim()]=decodeURIComponent(part.slice(i+1).trim())});return out}
function randomToken(){const bytes=new Uint8Array(32);crypto.getRandomValues(bytes);return btoa(String.fromCharCode(...bytes)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')}
async function auth(req,env,state){const token=parseCookies(req).sf_session;if(!token)return null;const row=await env.DB.prepare(`SELECT user_id,expires_at FROM sessions WHERE token=?`).bind(token).first();if(!row)return null;if(Number(row.expires_at)<Date.now()){await env.DB.prepare(`DELETE FROM sessions WHERE token=?`).bind(token).run();return null}const u=activeUser(state,row.user_id);return publicUser(u)}
async function newSession(env,user){const token=randomToken(),exp=Date.now()+1000*60*60*24*30;await env.DB.prepare(`DELETE FROM sessions WHERE expires_at<?`).bind(Date.now()).run();await env.DB.prepare(`INSERT INTO sessions(token,user_id,expires_at) VALUES(?,?,?)`).bind(token,user.id,exp).run();return{token,exp}}
function sessionCookie(token,maxAge=2592000){return `sf_session=${encodeURIComponent(token)}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${maxAge}; Secure`}

function headers(extra={}){return{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...extra}}
function json(obj,status=200,extra={}){return new Response(JSON.stringify(obj),{status,headers:headers({'Content-Type':'application/json; charset=utf-8',...extra})})}
async function readBody(req,limit=1024*1024){const text=await req.text();if(text.length>limit)throw new Error('too_large');if(!text)return{};try{return JSON.parse(text)}catch{throw new Error('bad_json')}}

function studentIds(state){return Object.values(state.users).filter(u=>u.role==='student'&&!u.disabled).map(u=>u.id).sort()}
function studentPayload(state,id){const u=activeUser(state,id);return{profile:publicUser(u),data:u.data,globalEvents:state.globalEvents,serverNow:nowIso()}}
function dayProgress(p){if(p.goalType==='check')return Number(p.completed||0)>=1?100:0;const t=Number(p.target||0),c=Number(p.completed||0);return t>0?Math.min(100,Math.round(c/t*100)):0}
function todayPlanProgress(data,date=todayKST()){const list=data.plans.day.filter(p=>p.date===date);return list.length?Math.round(list.reduce((a,p)=>a+dayProgress(p),0)/list.length):0}
function studySecondsOn(data,date=todayKST()){return data.studySessions.filter(s=>s.date===date).reduce((a,s)=>a+Math.max(0,Number(s.seconds)||0),0)+(data.activeStudy&&localDateFromISO(data.activeStudy.startAt)===date?Math.floor((Date.now()-new Date(data.activeStudy.startAt).getTime())/1000):0)}
function attendanceSummary(data,date=todayKST()){const recs=data.attendanceHistory.filter(r=>r.date===date),open=[...recs].reverse().find(r=>r.inAt&&!r.outAt);return{records:recs,checkedIn:!!open,current:open||null,firstIn:recs[0]?.inAt||null,lastOut:[...recs].reverse().find(r=>r.outAt)?.outAt||null}}
function adminOverview(state){const date=todayKST();return studentIds(state).map(id=>{const u=state.users[id],d=u.data,a=attendanceSummary(d,date);return{id,displayName:u.displayName,attendance:a,activeStudy:d.activeStudy,studySeconds:studySecondsOn(d,date),planProgress:todayPlanProgress(d,date),todayPlans:d.plans.day.filter(p=>p.date===date).length,updatedAt:d.updatedAt}})}
async function addAdminNotification(env,state,studentId,kind,title,body){const n={id:uid('noti'),studentId,kind,title,body,createdAt:nowIso(),read:false};state.adminNotifications.unshift(n);state.adminNotifications=state.adminNotifications.slice(0,1000);await saveKv(env,'adminNotifications',state.adminNotifications);return n}
async function checkAdminReminders(env,state){const now=Date.now();let changed=false;for(const e of state.adminCalendarEvents){if(!e.reminderAt||e.reminderSentAt)continue;const t=new Date(e.reminderAt).getTime();if(Number.isNaN(t)||t>now)continue;e.reminderSentAt=nowIso();state.adminNotifications.unshift({id:uid('noti'),studentId:'',kind:'admin_reminder',title:'STEPFLOW 일정 알림',body:`${e.title}${e.time?` · ${e.time}`:''}`,createdAt:nowIso(),read:false});changed=true}if(changed){state.adminNotifications=state.adminNotifications.slice(0,1000);await saveKv(env,'adminCalendarEvents',state.adminCalendarEvents);await saveKv(env,'adminNotifications',state.adminNotifications)}return changed}

async function requireRole(req,env,state,role){const u=await auth(req,env,state);if(!u)return{error:json({error:'login_required'},401)};if(u.role!==role)return{error:json({error:'forbidden'},403)};return{user:u}}

async function handleApi(req,env){await ensureDb(env);const url=new URL(req.url),p=url.pathname,state=await loadState(env);await checkAdminReminders(env,state);
 if(p==='/api/login'&&req.method==='POST'){const b=await readBody(req),id=safeStr(b.id,40).toLowerCase(),u=activeUser(state,id);if(!u)return json({error:'invalid_id'},401);const pu=publicUser(u),ses=await newSession(env,pu);return json({user:pu},200,{'Set-Cookie':sessionCookie(ses.token)})}
 if(p==='/api/logout'&&req.method==='POST'){const token=parseCookies(req).sf_session;if(token)await env.DB.prepare(`DELETE FROM sessions WHERE token=?`).bind(token).run();return json({ok:true},200,{'Set-Cookie':sessionCookie('',0)})}
 if(p==='/api/session'&&req.method==='GET'){const u=await auth(req,env,state);return u?json({user:u}):json({error:'login_required'},401)}

 if(p==='/api/me'&&req.method==='GET'){const a=await requireRole(req,env,state,'student');if(a.error)return a.error;return json(studentPayload(state,a.user.id))}
 if(p==='/api/plans'&&req.method==='PUT'){const a=await requireRole(req,env,state,'student');if(a.error)return a.error;const b=await readBody(req),stu=state.users[a.user.id];stu.data.plans=sanitizePlans(b.plans);stu.data.updatedAt=nowIso();await saveUser(env,stu);await touch(env,state);return json(studentPayload(state,a.user.id))}
 if(p==='/api/lectures'&&req.method==='PUT'){const a=await requireRole(req,env,state,'student');if(a.error)return a.error;const b=await readBody(req),stu=state.users[a.user.id];stu.data.lectures=sanitizeLectures(b.lectures);stu.data.updatedAt=nowIso();await saveUser(env,stu);await touch(env,state);return json(studentPayload(state,a.user.id))}
 if(p==='/api/attendance'&&req.method==='POST'){const a=await requireRole(req,env,state,'student');if(a.error)return a.error;const b=await readBody(req),stu=state.users[a.user.id],d=stu.data,date=todayKST();if(b.action==='in'){const open=d.attendanceHistory.find(r=>r.date===date&&!r.outAt);if(!open)d.attendanceHistory.push({id:uid('att'),date,inAt:nowIso(),outAt:null});d.updatedAt=nowIso();await saveUser(env,stu);await addAdminNotification(env,state,a.user.id,'attendance_in','입실 알림',`${a.user.displayName} 학생이 ${localHM(nowIso())} 입실했습니다.`)}else if(b.action==='out'){const open=[...d.attendanceHistory].reverse().find(r=>r.date===date&&!r.outAt);if(!open)return json({error:'not_checked_in'},409);open.outAt=nowIso();d.updatedAt=nowIso();await saveUser(env,stu);await addAdminNotification(env,state,a.user.id,'attendance_out','퇴실 알림',`${a.user.displayName} 학생이 ${localHM(open.outAt)} 퇴실했습니다.`)}else return json({error:'bad_action'},400);await touch(env,state);return json(studentPayload(state,a.user.id))}
 if(p==='/api/study/start'&&req.method==='POST'){const a=await requireRole(req,env,state,'student');if(a.error)return a.error;const stu=state.users[a.user.id],d=stu.data;if(d.activeStudy)return json({error:'already_running'},409);d.activeStudy={id:uid('run'),startAt:nowIso()};d.updatedAt=nowIso();await saveUser(env,stu);await touch(env,state);return json(studentPayload(state,a.user.id))}
 if(p==='/api/study/finish'&&req.method==='POST'){const a=await requireRole(req,env,state,'student');if(a.error)return a.error;const b=await readBody(req),stu=state.users[a.user.id],d=stu.data,run=d.activeStudy;if(!run)return json({error:'not_running'},409);const endAt=nowIso(),seconds=Math.max(1,Math.floor((new Date(endAt)-new Date(run.startAt))/1000));d.studySessions.push({id:uid('ses'),date:localDateFromISO(run.startAt),startAt:run.startAt,endAt,seconds,focus:Math.max(1,Math.min(3,Number(b.focus)||2)),subject:'',detail:'',note:''});d.activeStudy=null;d.updatedAt=nowIso();await saveUser(env,stu);await touch(env,state);return json(studentPayload(state,a.user.id))}
 if(p==='/api/events'&&req.method==='POST'){const a=await requireRole(req,env,state,'student');if(a.error)return a.error;const b=await readBody(req),ev=sanitizeEvent(b.event,a.user.id);if(!ev.title||!ev.startDate)return json({error:'missing_fields'},400);const stu=state.users[a.user.id];stu.data.events.push(ev);stu.data.updatedAt=nowIso();await saveUser(env,stu);await touch(env,state);return json(studentPayload(state,a.user.id))}
 if(p.startsWith('/api/events/')&&req.method==='DELETE'){const a=await requireRole(req,env,state,'student');if(a.error)return a.error;const id=decodeURIComponent(p.slice('/api/events/'.length)),stu=state.users[a.user.id];stu.data.events=stu.data.events.filter(e=>e.id!==id);stu.data.updatedAt=nowIso();await saveUser(env,stu);await touch(env,state);return json(studentPayload(state,a.user.id))}

 if(p==='/api/admin/overview'&&req.method==='GET'){const a=await requireRole(req,env,state,'admin');if(a.error)return a.error;return json({students:adminOverview(state),notifications:state.adminNotifications.slice(0,100),globalEvents:state.globalEvents,adminCalendarEvents:state.adminCalendarEvents,serverNow:nowIso()})}
 if(p==='/api/admin/student'&&req.method==='GET'){const a=await requireRole(req,env,state,'admin');if(a.error)return a.error;const id=safeStr(url.searchParams.get('id'),40).toLowerCase(),stu=activeUser(state,id);if(!stu||stu.role!=='student')return json({error:'not_found'},404);return json(studentPayload(state,id))}
 if(p==='/api/admin/student'&&req.method==='POST'){const a=await requireRole(req,env,state,'admin');if(a.error)return a.error;const b=await readBody(req),id=safeStr(b.id,40).toLowerCase();if(!validStudentId(id))return json({error:'bad_id'},400);if(state.users[id]&&!state.users[id].disabled)return json({error:'already_exists'},409);if(state.users[id]?.disabled){state.users[id].disabled=false;state.users[id].displayName=safeStr(b.displayName,60)||id;state.users[id].data=initialStudentData();state.users[id].deletedAt=''}else state.users[id]={...studentUser(id,safeStr(b.displayName,60)||id),createdAt:nowIso()};await saveUser(env,state.users[id]);await touch(env,state);return json({student:publicUser(state.users[id])})}
 if(p.startsWith('/api/admin/student/')&&req.method==='DELETE'){const a=await requireRole(req,env,state,'admin');if(a.error)return a.error;const id=safeStr(decodeURIComponent(p.slice('/api/admin/student/'.length)),40).toLowerCase(),stu=state.users[id];if(!stu||stu.role!=='student'||stu.disabled)return json({error:'not_found'},404);stu.disabled=true;stu.deletedAt=nowIso();await saveUser(env,stu);await touch(env,state);return json({ok:true})}
 if(p==='/api/admin/student-data'&&req.method==='PUT'){const a=await requireRole(req,env,state,'admin');if(a.error)return a.error;const id=safeStr(url.searchParams.get('id'),40).toLowerCase(),stu=activeUser(state,id);if(!stu||stu.role!=='student')return json({error:'not_found'},404);const b=await readBody(req,2*1024*1024);stu.data=normalizeStudentData(b.data);stu.data.updatedAt=nowIso();await saveUser(env,stu);await touch(env,state);return json(studentPayload(state,id))}
 if(p==='/api/admin/event'&&req.method==='POST'){const a=await requireRole(req,env,state,'admin');if(a.error)return a.error;const b=await readBody(req),target=safeStr(b.target,40),ev=sanitizeEvent(b.event,a.user.id);if(!ev.title||!ev.startDate)return json({error:'missing_fields'},400);if(target==='all'){state.globalEvents.push(ev);await saveKv(env,'globalEvents',state.globalEvents)}else{const stu=activeUser(state,target);if(!stu||stu.role!=='student')return json({error:'bad_target'},400);stu.data.events.push(ev);await saveUser(env,stu)}await touch(env,state);return json({ok:true})}
 if(p.startsWith('/api/admin/event/')&&req.method==='DELETE'){const a=await requireRole(req,env,state,'admin');if(a.error)return a.error;const id=decodeURIComponent(p.slice('/api/admin/event/'.length)),target=safeStr(url.searchParams.get('target'),40);if(target==='all'){state.globalEvents=state.globalEvents.filter(e=>e.id!==id);await saveKv(env,'globalEvents',state.globalEvents)}else{const stu=activeUser(state,target);if(!stu||stu.role!=='student')return json({error:'bad_target'},400);stu.data.events=stu.data.events.filter(e=>e.id!==id);await saveUser(env,stu)}await touch(env,state);return json({ok:true})}
 if(p==='/api/admin/calendar-event'&&req.method==='POST'){const a=await requireRole(req,env,state,'admin');if(a.error)return a.error;const b=await readBody(req),ev=sanitizeAdminEvent(b.event);if(!ev.title||!ev.startDate)return json({error:'missing_fields'},400);state.adminCalendarEvents.push(ev);await saveKv(env,'adminCalendarEvents',state.adminCalendarEvents);await touch(env,state);return json({event:ev})}
 if(p.startsWith('/api/admin/calendar-event/')&&req.method==='PUT'){const a=await requireRole(req,env,state,'admin');if(a.error)return a.error;const id=decodeURIComponent(p.slice('/api/admin/calendar-event/'.length)),idx=state.adminCalendarEvents.findIndex(e=>e.id===id);if(idx<0)return json({error:'not_found'},404);const b=await readBody(req),ev=sanitizeAdminEvent({...b.event,id,createdAt:state.adminCalendarEvents[idx].createdAt});if(!ev.title||!ev.startDate)return json({error:'missing_fields'},400);const old=state.adminCalendarEvents[idx];if(old.reminderAt===ev.reminderAt)ev.reminderSentAt=old.reminderSentAt;state.adminCalendarEvents[idx]=ev;await saveKv(env,'adminCalendarEvents',state.adminCalendarEvents);await touch(env,state);return json({event:ev})}
 if(p.startsWith('/api/admin/calendar-event/')&&req.method==='DELETE'){const a=await requireRole(req,env,state,'admin');if(a.error)return a.error;const id=decodeURIComponent(p.slice('/api/admin/calendar-event/'.length));state.adminCalendarEvents=state.adminCalendarEvents.filter(e=>e.id!==id);await saveKv(env,'adminCalendarEvents',state.adminCalendarEvents);await touch(env,state);return json({ok:true})}
 if(p==='/api/admin/notifications/read'&&req.method==='POST'){const a=await requireRole(req,env,state,'admin');if(a.error)return a.error;state.adminNotifications.forEach(n=>n.read=true);await saveKv(env,'adminNotifications',state.adminNotifications);return json({ok:true})}
 if(p==='/api/admin/export-state'&&req.method==='GET'){const a=await requireRole(req,env,state,'admin');if(a.error)return a.error;return new Response(JSON.stringify(state,null,2),{status:200,headers:headers({'Content-Type':'application/json; charset=utf-8','Content-Disposition':'attachment; filename="stepflow-state.json"'})})}
 if(p==='/api/admin/import-state'&&req.method==='POST'){const a=await requireRole(req,env,state,'admin');if(a.error)return a.error;const body=await readBody(req,8*1024*1024),st=await importState(env,body);return json({ok:true,students:Object.values(st.users).filter(u=>u.role==='student'&&!u.disabled).length})}

 if(p==='/api/push/public-key'&&req.method==='GET'){const u=await auth(req,env,state);if(!u)return json({error:'login_required'},401);return json({available:false,publicKey:''})}
 if(p==='/api/push/subscribe'&&req.method==='POST'){const u=await auth(req,env,state);if(!u)return json({error:'login_required'},401);return json({ok:true,available:false})}
 return json({error:'not_found'},404);
}

export default {
 async fetch(request,env){try{const url=new URL(request.url);if(url.pathname.startsWith('/api/'))return await handleApi(request,env);return env.ASSETS.fetch(request)}catch(e){console.error(e);const status=e?.message==='too_large'?413:400;return json({error:e?.message||'server_error'},status)}},
 async scheduled(_controller,env,_ctx){try{const state=await loadState(env);await checkAdminReminders(env,state)}catch(e){console.error('scheduled reminder failed',e)}}
};
